refactoring for lower-id and upper-id

diff --git a/bin/pve-autosnap b/bin/pve-autosnap
--- a/bin/pve-autosnap
+++ b/bin/pve-autosnap
@@ -20,10 +20,11 @@
 # pve definitions
 # ----------------------------------------------------------------------------
 
+pve_autosnap='pve-autosnap'
 pve_kvm_manager='/usr/sbin/qm'
 pve_lxc_manager='/usr/sbin/pct'
-pve_minvmid='100'
-pve_maxvmid='1000000'
+pve_lower_id='100'
+pve_upper_id='1000000'
 
 # ----------------------------------------------------------------------------
 # kvm/lxc manager definitions
@@ -43,8 +44,8 @@ cmd_delete_snapshot='delsnapshot'
 
 opt_vmid='help'
 opt_keep='1'
-opt_minvmid="${pve_minvmid}"
-opt_maxvmid="${pve_maxvmid}"
+opt_lower_id="${pve_lower_id}"
+opt_upper_id="${pve_upper_id}"
 opt_exclude=''
 opt_include=''
 opt_prefix='AUTOSNAP'
@@ -56,18 +57,16 @@ opt_debug='no'
 # get the program name
 # ----------------------------------------------------------------------------
 
-if [ "no${0}ne" != 'none' ]
+if [ "${0:-not-set}" != 'not-set' ]
 then
     pve_autosnap="${0}"
-else
-    pve_autosnap="pve-autosnap"
 fi
 
 # ----------------------------------------------------------------------------
 # parse the <vmid> positional parameter
 # ----------------------------------------------------------------------------
 
-if [ "${#}" -gt '0' ] && [ "no${1}ne" != 'none' ]
+if [ "${#}" -gt '0' ] && [ "${1:-not-set}" != 'not-set' ]
 then
     case "${1}" in
         --help)
@@ -89,7 +88,7 @@ fi
 # parse the <keep> positional parameter
 # ----------------------------------------------------------------------------
 
-if [ "${#}" -gt '0' ] && [ "no${1}ne" != 'none' ]
+if [ "${#}" -gt '0' ] && [ "${1:-not-set}" != 'not-set' ]
 then
     case "${1}" in
         --help)
@@ -123,10 +122,18 @@ do
     esac
     case "${1}" in
         --minvmid=*)
-            opt_minvmid="${arg_value}"
+            echo "--minvmid is deprecated, use --lower-id instead"
+            opt_lower_id="${arg_value}"
             ;;
         --maxvmid=*)
-            opt_maxvmid="${arg_value}"
+            echo "--maxvmid is deprecated, use --upper-id instead"
+            opt_upper_id="${arg_value}"
+            ;;
+        --lower-id=*)
+            opt_lower_id="${arg_value}"
+            ;;
+        --upper-id=*)
+            opt_upper_id="${arg_value}"
             ;;
         --exclude=*)
             opt_exclude="$(echo "${arg_value}" | tr ',' ' ')"
@@ -177,8 +184,8 @@ Arguments:
 
 Options:
 
-    --minvmid={vmid}            specifies the first vmid (default is 100)
-    --maxvmid={vmid}            specifies the last vmid (default is 9999)
+    --lower-id={vmid}           specifies the lower vmid (default is 100)
+    --upper-id={vmid}           specifies the upper vmid (default is 1000000)
     --exclude={vmid,vmid,...}   specifies the list of vmid to exclude
     --include={vmid,vmid,...}   specifies the list of vmid to include
     --tag={tag}                 specifies an optional snapshot tag (snapshots will be named "AUTOSNAP_{tag}_YYYYMMDD_HHMMSS")
@@ -219,28 +226,28 @@ else
 fi
 
 # ----------------------------------------------------------------------------
-# verify the '--minvmid={vmid}' option
+# verify the '--lower-id={vmid}' option
 # ----------------------------------------------------------------------------
 
-if [ "${opt_minvmid}" -ge "${pve_minvmid}" ] \
-&& [ "${opt_minvmid}" -le "${pve_maxvmid}" ]
+if [ "${opt_lower_id}" -ge "${pve_lower_id}" ] \
+&& [ "${opt_lower_id}" -le "${pve_upper_id}" ]
 then
     : # no-op
 else
-    echo "the minimum vmid is not in the range [${pve_minvmid},${pve_maxvmid}]"
+    echo "the lower-id is not in the range [${pve_lower_id},${pve_upper_id}]"
     exit 1
 fi
 
 # ----------------------------------------------------------------------------
-# verify the '--maxvmid={vmid}' option
+# verify the '--upper-id={vmid}' option
 # ----------------------------------------------------------------------------
 
-if [ "${opt_maxvmid}" -ge "${pve_minvmid}" ] \
-&& [ "${opt_maxvmid}" -le "${pve_maxvmid}" ]
+if [ "${opt_upper_id}" -ge "${pve_lower_id}" ] \
+&& [ "${opt_upper_id}" -le "${pve_upper_id}" ]
 then
     : # no-op
 else
-    echo "the maximum vmid is not in the range [${pve_minvmid},${pve_maxvmid}]"
+    echo "the upper-id is not in the range [${pve_lower_id},${pve_upper_id}]"
     exit 1
 fi
 
@@ -252,12 +259,12 @@ if [ "${opt_exclude:-not-set}" != 'not-set' ]
 then
     for excluded_vm in ${opt_exclude}
     do
-        if [ "${excluded_vm}" -ge "${opt_minvmid}" ] \
-        && [ "${excluded_vm}" -le "${opt_maxvmid}" ]
+        if [ "${excluded_vm}" -ge "${opt_lower_id}" ] \
+        && [ "${excluded_vm}" -le "${opt_upper_id}" ]
         then
             : # no-op
         else
-            echo "error: the excluded vmid <${excluded_vm}> is not in the range [${opt_minvmid},${opt_maxvmid}]"
+            echo "error: the excluded vmid <${excluded_vm}> is not in the range [${opt_lower_id},${opt_upper_id}]"
             exit 1
         fi
     done
@@ -271,12 +278,12 @@ if [ "${opt_include:-not-set}" != 'not-set' ]
 then
     for included_vm in ${opt_include}
     do
-        if [ "${included_vm}" -ge "${opt_minvmid}" ] \
-        && [ "${included_vm}" -le "${opt_maxvmid}" ]
+        if [ "${included_vm}" -ge "${opt_lower_id}" ] \
+        && [ "${included_vm}" -le "${opt_upper_id}" ]
         then
             : # no-op
         else
-            echo "error: the included vmid <${included_vm}> is not in the range [${opt_minvmid},${opt_maxvmid}]"
+            echo "error: the included vmid <${included_vm}> is not in the range [${opt_lower_id},${opt_upper_id}]"
             exit 1
         fi
     done
@@ -327,8 +334,8 @@ then
             fi
         done
         if [ "${is_excluded}" = 'no' ] \
-        && [ "${vmid}" -ge "${opt_minvmid}" ] \
-        && [ "${vmid}" -le "${opt_maxvmid}" ]
+        && [ "${vmid}" -ge "${opt_lower_id}" ] \
+        && [ "${vmid}" -le "${opt_upper_id}" ]
         then
             ${pve_autosnap} "${vmid}" "${opt_keep}" --tag="${opt_tag}"
         fi
@@ -357,13 +364,26 @@ then
             fi
         done
         if [ "${is_included}" = 'yes' ] \
-        && [ "${vmid}" -ge "${opt_minvmid}" ] \
-        && [ "${vmid}" -le "${opt_maxvmid}" ]
+        && [ "${vmid}" -ge "${opt_lower_id}" ] \
+        && [ "${vmid}" -le "${opt_upper_id}" ]
         then
             ${pve_autosnap} "${vmid}" "${opt_keep}" --tag="${opt_tag}"
         fi
     done
     exit 0
+fi
+
+# ----------------------------------------------------------------------------
+# check if the given <vmid> is in the range {lower_id,upper_id}
+# ----------------------------------------------------------------------------
+
+if [ "${opt_vmid}" -ge "${opt_lower_id}" ] \
+&& [ "${opt_vmid}" -le "${opt_upper_id}" ]
+then
+    : # no-op
+else
+    echo "error: the given vmid <${opt_vmid}> is not in the range [${opt_lower_id},${opt_upper_id}]"
+    exit 1
 fi
 
 # ----------------------------------------------------------------------------
